source : https://www.youtube.com/watch?v=xaQpLz6QkVQ

In [93]:
import tensorflow as tf
from tensorflow.keras import layers

In [94]:
from keras import Model
from keras.layers import Input, Dense, Bidirectional, LSTM, RepeatVector, TimeDistributed
from sklearn.preprocessing import MinMaxScaler
from numpy import array, hstack
import numpy as np

In [95]:
data_X1 = [21,26,31,36,31,46,51,56,61,65,70,75,80,85,90,95,100,105,110,115]
data_X2 = [2,5,8,11,14,17,20,23,26,29,32,35,38,41,44,47,50,53,56,59]
data_X3 = [13,17,21,25,29,33,37,41,44,48,52,56,60,64,68,72,76,80,84,88]

In [96]:
data_X1 = np.array(data_X1)
data_X2 = np.array(data_X2)
data_X3 = np.array(data_X3)

In [97]:
data_X1


array([ 21,  26,  31,  36,  31,  46,  51,  56,  61,  65,  70,  75,  80,
        85,  90,  95, 100, 105, 110, 115])

In [98]:
# step 1: convert to [rows, column] structure
data_X1 = data_X1.reshape((len(data_X1), 1))
data_X2 = data_X2.reshape((len(data_X2), 1))
data_X3 = data_X3.reshape((len(data_X3), 1))

In [99]:
data_X1.shape

(20, 1)

In [100]:
data_X1

array([[ 21],
       [ 26],
       [ 31],
       [ 36],
       [ 31],
       [ 46],
       [ 51],
       [ 56],
       [ 61],
       [ 65],
       [ 70],
       [ 75],
       [ 80],
       [ 85],
       [ 90],
       [ 95],
       [100],
       [105],
       [110],
       [115]])

In [101]:
print("data_X1.shape", data_X1.shape)
print("data_X2.shape", data_X2.shape)
print("data_X3.shape", data_X3.shape)

data_X1.shape (20, 1)
data_X2.shape (20, 1)
data_X3.shape (20, 1)


In [102]:
# step 2 : Do scalling
data_scalar = MinMaxScaler(feature_range = (0,1))
data_X1_scaled =  data_scalar.fit_transform(data_X1)
data_X2_scaled =  data_scalar.fit_transform(data_X2)
data_X3_scaled =  data_scalar.fit_transform(data_X3)

In [103]:
data_X1_scaled

array([[0.        ],
       [0.05319149],
       [0.10638298],
       [0.15957447],
       [0.10638298],
       [0.26595745],
       [0.31914894],
       [0.37234043],
       [0.42553191],
       [0.46808511],
       [0.5212766 ],
       [0.57446809],
       [0.62765957],
       [0.68085106],
       [0.73404255],
       [0.78723404],
       [0.84042553],
       [0.89361702],
       [0.94680851],
       [1.        ]])

In [135]:
# step 3: horizontaly stack columns
dataset_stacked = hstack((data_X1_scaled, data_X2_scaled, data_X3_scaled))
dataset_stacked = np.array(dataset_stacked)
print("dataset_stacked.shape", dataset_stacked.shape)
print("final dataset =>", dataset_stacked)

dataset_stacked.shape (20, 3)
final dataset => [[0.         0.         0.        ]
 [0.05319149 0.05263158 0.05333333]
 [0.10638298 0.10526316 0.10666667]
 [0.15957447 0.15789474 0.16      ]
 [0.10638298 0.21052632 0.21333333]
 [0.26595745 0.26315789 0.26666667]
 [0.31914894 0.31578947 0.32      ]
 [0.37234043 0.36842105 0.37333333]
 [0.42553191 0.42105263 0.41333333]
 [0.46808511 0.47368421 0.46666667]
 [0.5212766  0.52631579 0.52      ]
 [0.57446809 0.57894737 0.57333333]
 [0.62765957 0.63157895 0.62666667]
 [0.68085106 0.68421053 0.68      ]
 [0.73404255 0.73684211 0.73333333]
 [0.78723404 0.78947368 0.78666667]
 [0.84042553 0.84210526 0.84      ]
 [0.89361702 0.89473684 0.89333333]
 [0.94680851 0.94736842 0.94666667]
 [1.         1.         1.        ]]


In [136]:
# prepare the dataset
input_timesteps = 3
input_features = 3
output_timesteps = 1
output_features = 3

data_Y = []
data_X = []



In [137]:
for i in range(0, ((len(data_X1)) - (input_timesteps + output_timesteps))):
  tmpY2d = []
  for i_row in range(i, (i + output_timesteps)):
    tmpYr = []
    for i_col in range(0, output_features):
      tmpYr.append(dataset_stacked[i_row][i_col])
    tmpY2d.append(tmpYr)
  data_Y.append(tmpY2d)
  tmpX2d = []
  for j_row in range((i + output_timesteps), (i + output_timesteps + input_timesteps)):
    tmpXr = []
    for j_col in range(0, input_features):
      tmpXr.append(dataset_stacked[j_row][j_col])
    tmpX2d.append(tmpXr)
  data_X.append(tmpX2d)

In [138]:
dataset_stacked

array([[0.        , 0.        , 0.        ],
       [0.05319149, 0.05263158, 0.05333333],
       [0.10638298, 0.10526316, 0.10666667],
       [0.15957447, 0.15789474, 0.16      ],
       [0.10638298, 0.21052632, 0.21333333],
       [0.26595745, 0.26315789, 0.26666667],
       [0.31914894, 0.31578947, 0.32      ],
       [0.37234043, 0.36842105, 0.37333333],
       [0.42553191, 0.42105263, 0.41333333],
       [0.46808511, 0.47368421, 0.46666667],
       [0.5212766 , 0.52631579, 0.52      ],
       [0.57446809, 0.57894737, 0.57333333],
       [0.62765957, 0.63157895, 0.62666667],
       [0.68085106, 0.68421053, 0.68      ],
       [0.73404255, 0.73684211, 0.73333333],
       [0.78723404, 0.78947368, 0.78666667],
       [0.84042553, 0.84210526, 0.84      ],
       [0.89361702, 0.89473684, 0.89333333],
       [0.94680851, 0.94736842, 0.94666667],
       [1.        , 1.        , 1.        ]])

In [139]:
data_X = np.array(data_X)
data_Y = np.array(data_Y)

print("shape of input data ", data_X.shape)
print("input data => ", data_X)
print("shape of output data ", data_Y.shape)
print("output data => ", data_Y)


shape of input data  (16, 3, 3)
input data =>  [[[0.05319149 0.05263158 0.05333333]
  [0.10638298 0.10526316 0.10666667]
  [0.15957447 0.15789474 0.16      ]]

 [[0.10638298 0.10526316 0.10666667]
  [0.15957447 0.15789474 0.16      ]
  [0.10638298 0.21052632 0.21333333]]

 [[0.15957447 0.15789474 0.16      ]
  [0.10638298 0.21052632 0.21333333]
  [0.26595745 0.26315789 0.26666667]]

 [[0.10638298 0.21052632 0.21333333]
  [0.26595745 0.26315789 0.26666667]
  [0.31914894 0.31578947 0.32      ]]

 [[0.26595745 0.26315789 0.26666667]
  [0.31914894 0.31578947 0.32      ]
  [0.37234043 0.36842105 0.37333333]]

 [[0.31914894 0.31578947 0.32      ]
  [0.37234043 0.36842105 0.37333333]
  [0.42553191 0.42105263 0.41333333]]

 [[0.37234043 0.36842105 0.37333333]
  [0.42553191 0.42105263 0.41333333]
  [0.46808511 0.47368421 0.46666667]]

 [[0.42553191 0.42105263 0.41333333]
  [0.46808511 0.47368421 0.46666667]
  [0.5212766  0.52631579 0.52      ]]

 [[0.46808511 0.47368421 0.46666667]
  [0.5212766

In [140]:
input_features

3

In [141]:
def define_model():
  encoder_inputs = Input(shape = (input_timesteps, input_features))
  encoder = Bidirectional(LSTM(units = 16, return_sequences=False))(encoder_inputs)
  repeat_output = RepeatVector(output_timesteps)(encoder)
  decoder = Bidirectional(LSTM(units = 16, return_sequences=True))(repeat_output)



  out = TimeDistributed(Dense(output_features))(decoder)
  model = Model(encoder_inputs , out)

  model.compile(loss = 'mae', optimizer = 'adam', metrics=[tf.keras.metrics.MeanAbsoluteError()])
  model.summary()
  return model

In [142]:
# call the model
model = define_model()

Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 3, 3)]            0         
                                                                 
 bidirectional_10 (Bidirect  (None, 32)                2560      
 ional)                                                          
                                                                 
 repeat_vector_5 (RepeatVec  (None, 1, 32)             0         
 tor)                                                            
                                                                 
 bidirectional_11 (Bidirect  (None, 1, 32)             6272      
 ional)                                                          
                                                                 
 time_distributed_5 (TimeDi  (None, 1, 3)              99        
 stributed)                                                

In [143]:
type(data_X)

numpy.ndarray

In [144]:
data_X[1]

array([[0.10638298, 0.10526316, 0.10666667],
       [0.15957447, 0.15789474, 0.16      ],
       [0.10638298, 0.21052632, 0.21333333]])

In [145]:
data_Y[1]

array([[0.05319149, 0.05263158, 0.05333333]])

In [146]:
# fit the model
model.fit(data_X, data_Y, epochs = 4, batch_size=2, verbose = 1)


Epoch 1/4
8/8 [==============================] - 7s 5ms/step - loss: 0.3639 - mean_absolute_error: 0.3639
Epoch 2/4
8/8 [==============================] - 0s 6ms/step - loss: 0.3232 - mean_absolute_error: 0.3232
Epoch 3/4
8/8 [==============================] - 0s 5ms/step - loss: 0.2681 - mean_absolute_error: 0.2681
Epoch 4/4
8/8 [==============================] - 0s 5ms/step - loss: 0.2091 - mean_absolute_error: 0.2091


In [147]:
dataset_stacked

array([[0.        , 0.        , 0.        ],
       [0.05319149, 0.05263158, 0.05333333],
       [0.10638298, 0.10526316, 0.10666667],
       [0.15957447, 0.15789474, 0.16      ],
       [0.10638298, 0.21052632, 0.21333333],
       [0.26595745, 0.26315789, 0.26666667],
       [0.31914894, 0.31578947, 0.32      ],
       [0.37234043, 0.36842105, 0.37333333],
       [0.42553191, 0.42105263, 0.41333333],
       [0.46808511, 0.47368421, 0.46666667],
       [0.5212766 , 0.52631579, 0.52      ],
       [0.57446809, 0.57894737, 0.57333333],
       [0.62765957, 0.63157895, 0.62666667],
       [0.68085106, 0.68421053, 0.68      ],
       [0.73404255, 0.73684211, 0.73333333],
       [0.78723404, 0.78947368, 0.78666667],
       [0.84042553, 0.84210526, 0.84      ],
       [0.89361702, 0.89473684, 0.89333333],
       [0.94680851, 0.94736842, 0.94666667],
       [1.        , 1.        , 1.        ]])

In [148]:
test_dataX = []
test_dataX.append(dataset_stacked[0])
test_dataX.append(dataset_stacked[1])
test_dataX.append(dataset_stacked[2])


In [149]:
test_dataX

[array([0., 0., 0.]),
 array([0.05319149, 0.05263158, 0.05333333]),
 array([0.10638298, 0.10526316, 0.10666667])]

In [150]:
# reshape the data into 3-D numpy array
test_dataX = np.reshape(test_dataX, (1, input_timesteps, input_features))
print("test dataset => ", test_dataX)

# run for the prediction output
pred_output= model.predict(test_dataX)
print("prediction output =>", pred_output)

# invert the scalling to get forecast vallue
inverted_output = data_scalar.inverse_transform(pred_output[0])
print("obtained prediction =>", inverted_output)

test dataset =>  [[[0.         0.         0.        ]
  [0.05319149 0.05263158 0.05333333]
  [0.10638298 0.10526316 0.10666667]]]
1/1 [==============================] - 2s 2s/step
prediction output => [[[0.11165572 0.11033125 0.08590353]]]
obtained prediction => [[21.37418  21.274843 19.442766]]
